### ISSUE TITLE
Rename to ortc-quic?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/p2p-webtransport#137]
Should this spec / repo be renamed ortc-quic to avoid confusion as a potential webrtc work item?

Also, it may be worth updating the README to point to the client/server work happening in WebTransport and how the two work items may relate to one-another (if at all)

**Comment by aboba** [comment]
The current specification extends the WebTransport API to support P2P operation.  Since it is no longer based on ORTC, "ORTC-QUIC" would be misleading; "P2P WebTransport" might be better.

**Comment by dontcallmedom** [comment]
I've renamed the repo to `p2p-webtransport` - I guess the spec title should be amended in a similar way.
