### ISSUE TITLE
Clarify status of documents

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/p2p-webtransport#140]
I think https://w3c.github.io/p2p-webtransport/cs.html has been overtaken by WebTransport - if so, that may be worth clarifying in the document itself.

https://w3c.github.io/p2p-webtransport/ should state in its Status section it is a CG report using the appropriate language (see e.g. the boilerplate defined in https://www.w3.org/community/reports/reqs/ )

**Comment by aboba** [comment]
The required boilerplate was pulled in automatically.
