### ISSUE TITLE
Firewall traversal

### ISSUE THREAD

**Issue by aboba** [w3c/p2p-webtransport#91]
From @johnwason:

Does the ICE-free client-server option utilize the standard QUIC HTTP port with an upgrade system like websockets? Many firewalls will block anything that is a non-HTTP port.

**Comment by pthatcherg** [comment]
I assume you mean the server port, not the client port.

The URL passed into the constructor can specify any port.  But it's a good question of what port we should use if the port isn't specified.  Do we use an HTTP port?  Or do we require the port in the URL so the JS must be explicit?  In general I prefer explicit over implicit.

**Comment by johnwason** [comment]
Yes, the server port. With websockets, it is really easy to open up a bidirectional stream and access it within the web server itself. (ASP.NET has a really slick interface for accepting websocket connections.) Having a QUIC HTTP server able to accept QUIC raw transports in a similar way using an upgrade header would be very useful for things like real-time gaming or data exchange.

**Comment by pthatcherg** [comment]
That should work.  Even if the default port isn't what you want (or we don't allow a default port), you can specify the server port to use in the URL.

**Comment by johnwason** [comment]
@pthatcherg I am still a little unclear about the connection process. Will the QuicTransport connection include HTTP headers upon the initial connect? What will enable the switch from HTTP mode to raw mode? Will the connection require masking like current websockets? (I don't think masking is required since the transport is already encrypted)

**Comment by pthatcherg** [comment]
That brings up an interesting question that should probably be discussed in a separate github issue: what should our ALPN be?  Victor was suggesting to me that it would be more secure for p2p vs. client/server and that it should be different than "hq".  Perhaps something like "wq" (web quic) and "wq2q" (web p2p quic).  But again, we should probably open a separate issue for that.

**Comment by johnwason** [comment]
@aboba Interesting, I wasn't aware of TLS ALPN extensions. Some applications use websockets as part of an HTTP API, for instance SignalR uses HTTP cookies and query tokens to match the websocket to the active HTTP "session". Is this capability being considered? It would effectively make the new transport "websockets V2" (or V3 to match HTTP/3).

**Comment by aboba** [comment]
This question should be clarified by the WebTransport protocol specifications. See: 
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http2
